# Generated by Django 3.0.5 on 2020-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('time_price', models.FloatField()),
                ('when_time', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('day_price', models.FloatField()),
                ('when_day', models.CharField(max_length=50)),
                ('month_price', models.FloatField()),
                ('when_month', models.CharField(max_length=50)),
            ],
        ),
    ]
